In [30]:
import numpy as np
import scipy
import sympy
import data_import

# Data setup

In [31]:
# print(np.dot(N.T, N))

In [38]:
# cylce of 2 with large min err ~= 10
# Q = np.array([[ 7.95775e-02,  3.97311e-02,  3.51801e-02, -2.44704e-03,  1.60629e-02,  2.66396e-02, -3.95693e-02,  1.97666e-02,  1.78489e-03,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00],
#        [ 3.97311e-02,  7.95775e-02,  3.61294e-02, -3.06395e-04,  1.79985e-02,  2.81915e-02,  3.97365e-02,  0.00000e+00,  0.00000e+00,  3.56234e-02,  2.86173e-02, -1.10943e-03,  2.88375e-02,  1.81956e-02,  1.27347e-03,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00],
#        [ 3.51801e-02,  3.61294e-02,  7.95775e-02,  1.63890e-02,  3.12081e-02,  3.73608e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  1.76687e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.56910e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.58461e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.53464e-02,  1.39357e-02, -1.34265e-02],
#        [-2.44704e-03, -3.06395e-04,  1.63890e-02,  7.95775e-02,  3.53455e-02,  2.78603e-02,  0.00000e+00,  3.56818e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.76355e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.97737e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.74122e-02,  0.00000e+00,  0.00000e+00,  1.75080e-02,  0.00000e+00,  0.00000e+00],
#        [ 1.60629e-02,  1.79985e-02,  3.12081e-02,  3.53455e-02,  7.95775e-02,  3.77937e-02,  0.00000e+00,  0.00000e+00,  3.56451e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.33265e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.77981e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.50873e-02,  0.00000e+00,  0.00000e+00,  1.21881e-02,  0.00000e+00],
#        [ 2.66396e-02,  2.81915e-02,  3.73608e-02,  2.78603e-02,  3.77937e-02,  7.95775e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.71615e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.76887e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.97694e-02,  0.00000e+00,  0.00000e+00,  2.54907e-02],
#        [-3.95693e-02,  3.97365e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  7.95775e-02, -1.60361e-02,  2.39357e-03,  3.46691e-02,  2.71642e-02, -3.14462e-03,  2.73959e-02,  1.63598e-02, -7.64592e-04,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00],
#        [ 1.97666e-02,  0.00000e+00,  0.00000e+00,  3.56818e-02,  0.00000e+00,  0.00000e+00, -1.60361e-02,  7.95775e-02,  3.53835e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.74491e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.61525e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.73435e-02,  0.00000e+00,  0.00000e+00,  3.15103e-02,  0.00000e+00,  0.00000e+00],
#        [ 1.78489e-03,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.56451e-02,  0.00000e+00,  2.39357e-03,  3.53835e-02,  7.95775e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.52200e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.83397e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.97701e-02,  0.00000e+00,  0.00000e+00,  2.77486e-02,  0.00000e+00],
#        [ 0.00000e+00,  3.56234e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.46691e-02,  0.00000e+00,  0.00000e+00,  7.95775e-02,  3.79351e-02,  1.67232e-02,  3.80299e-02,  3.20523e-02,  1.88544e-02,  3.62154e-02,  3.60652e-02, -1.89662e-02,  1.27197e-02,  2.41458e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00],
#        [ 0.00000e+00,  2.86173e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.71642e-02,  0.00000e+00,  0.00000e+00,  3.79351e-02,  7.95775e-02,  2.68354e-02,  3.97875e-02,  3.76710e-02,  2.85459e-02, -2.95567e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.90747e-02, -3.97838e-02, -2.82570e-02, -4.73705e-04,  0.00000e+00,  0.00000e+00,  0.00000e+00],
#        [ 0.00000e+00, -1.10943e-03,  1.76687e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00, -3.14462e-03,  0.00000e+00,  0.00000e+00,  1.67232e-02,  2.68354e-02,  7.95775e-02,  2.65995e-02,  3.48634e-02,  3.97174e-02,  0.00000e+00,  9.13846e-05,  0.00000e+00,  0.00000e+00,  0.00000e+00,  4.45436e-04,  0.00000e+00,  0.00000e+00,  0.00000e+00, -1.62257e-02, -2.72041e-02, -3.95217e-02],
#        [ 0.00000e+00,  2.88375e-02,  0.00000e+00,  2.76355e-02,  0.00000e+00,  0.00000e+00,  2.73959e-02,  3.74491e-02,  0.00000e+00,  3.80299e-02,  3.97875e-02,  2.65995e-02,  7.95775e-02,  3.75673e-02,  2.83232e-02,  0.00000e+00,  0.00000e+00,  2.84123e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.97875e-02,  0.00000e+00,  0.00000e+00,  3.78656e-02,  0.00000e+00,  0.00000e+00],
#        [ 0.00000e+00,  1.81956e-02,  0.00000e+00,  0.00000e+00,  2.33265e-02,  0.00000e+00,  1.63598e-02,  0.00000e+00,  3.52200e-02,  3.20523e-02,  3.76710e-02,  3.48634e-02,  3.75673e-02,  7.95775e-02,  3.59488e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  1.20917e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.57701e-02,  0.00000e+00,  0.00000e+00,  3.78297e-02,  0.00000e+00],
#        [ 0.00000e+00,  1.27347e-03,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.71615e-02, -7.64592e-04,  0.00000e+00,  0.00000e+00,  1.88544e-02,  2.85459e-02,  3.97174e-02,  2.83232e-02,  3.59488e-02,  7.95775e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  1.64068e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.80557e-02,  0.00000e+00,  0.00000e+00,  3.97263e-02],
#        [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.62154e-02, -2.95567e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  7.95775e-02,  3.97871e-02, -2.77562e-03,  2.71926e-02,  3.50759e-02, -3.97823e-02,  2.99731e-02,  2.23720e-03, -2.62835e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00],
#        [ 0.00000e+00,  0.00000e+00,  3.56910e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.60652e-02,  0.00000e+00,  9.13846e-05,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.97871e-02,  7.95775e-02, -2.41745e-03,  2.74535e-02,  3.52439e-02,  3.97872e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.62927e-02,  2.89733e-02,  4.51145e-03],
#        [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  3.97737e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.61525e-02,  0.00000e+00, -1.89662e-02,  0.00000e+00,  0.00000e+00,  2.84123e-02,  0.00000e+00,  0.00000e+00, -2.77562e-03, -2.41745e-03,  7.95775e-02,  2.70789e-02,  1.62910e-02,  0.00000e+00,  2.81950e-02,  0.00000e+00,  0.00000e+00,  1.84840e-02,  0.00000e+00,  0.00000e+00],
#        [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.77981e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.83397e-02,  1.27197e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  1.20917e-02,  0.00000e+00,  2.71926e-02,  2.74535e-02,  2.70789e-02,  7.95775e-02,  3.76842e-02,  0.00000e+00,  0.00000e+00,  2.74717e-02,  0.00000e+00,  0.00000e+00, -2.51793e-04,  0.00000e+00],
#        [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.76887e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.41458e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  1.64068e-02,  3.50759e-02,  3.52439e-02,  1.62910e-02,  3.76842e-02,  7.95775e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.72723e-02,  0.00000e+00,  0.00000e+00,  1.43512e-02],
#        [ 0.00000e+00,  0.00000e+00,  3.58461e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.90747e-02,  4.45436e-04,  0.00000e+00,  0.00000e+00,  0.00000e+00, -3.97823e-02,  3.97872e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  7.95775e-02, -2.94994e-02, -1.52501e-03,  2.68145e-02,  3.61461e-02,  2.87295e-02,  4.15950e-03],
#        [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  2.74122e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.73435e-02,  0.00000e+00,  0.00000e+00, -3.97838e-02,  0.00000e+00,  3.97875e-02,  0.00000e+00,  0.00000e+00,  2.99731e-02,  0.00000e+00,  2.81950e-02,  0.00000e+00,  0.00000e+00, -2.94994e-02,  7.95775e-02,  2.78117e-02, -1.53822e-04,  3.79595e-02,  0.00000e+00,  0.00000e+00],
#        [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.50873e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.97701e-02,  0.00000e+00, -2.82570e-02,  0.00000e+00,  0.00000e+00,  3.57701e-02,  0.00000e+00,  2.23720e-03,  0.00000e+00,  0.00000e+00,  2.74717e-02,  0.00000e+00, -1.52501e-03,  2.78117e-02,  7.95775e-02,  2.83467e-02,  0.00000e+00,  2.86084e-02,  0.00000e+00],
#        [ 0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.97694e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00, -4.73705e-04,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.80557e-02, -2.62835e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.72723e-02,  2.68145e-02, -1.53822e-04,  2.83467e-02,  7.95775e-02,  0.00000e+00,  0.00000e+00,  2.64317e-02],
#        [ 0.00000e+00,  0.00000e+00,  2.53464e-02,  1.75080e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.15103e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00, -1.62257e-02,  3.78656e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  3.62927e-02,  1.84840e-02,  0.00000e+00,  0.00000e+00,  3.61461e-02,  3.79595e-02,  0.00000e+00,  0.00000e+00,  7.95775e-02,  3.76056e-02,  2.03189e-02],
#        [ 0.00000e+00,  0.00000e+00,  1.39357e-02,  0.00000e+00,  1.21881e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  2.77486e-02,  0.00000e+00,  0.00000e+00, -2.72041e-02,  0.00000e+00,  3.78297e-02,  0.00000e+00,  0.00000e+00,  2.89733e-02,  0.00000e+00, -2.51793e-04,  0.00000e+00,  2.87295e-02,  0.00000e+00,  2.86084e-02,  0.00000e+00,  3.76056e-02,  7.95775e-02,  3.03800e-02],
#        [ 0.00000e+00,  0.00000e+00, -1.34265e-02,  0.00000e+00,  0.00000e+00,  2.54907e-02,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00, -3.95217e-02,  0.00000e+00,  0.00000e+00,  3.97263e-02,  0.00000e+00,  4.51145e-03,  0.00000e+00,  0.00000e+00,  1.43512e-02,  4.15950e-03,  0.00000e+00,  0.00000e+00,  2.64317e-02,  2.03189e-02,  3.03800e-02,  7.95775e-02]])
# N = np.array([[ 0.0504832 , -0.00333431, -0.421931  , -0.999939  , -0.893343  , -0.70804   ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [-0.998725  , -0.999994  , -0.906628  ,  0.0110347 , -0.449375  , -0.706172  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [-0.0504832 ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        , -0.0545359 , -0.891844  , -0.999984  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.998725  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        , -0.998512  ,  0.452342  , -0.00563031,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.00333431,  0.        ,  0.        ,  0.        ,  0.        ,  0.0545359 ,  0.        ,  0.        , -0.442449  , -0.69237   , -0.999699  , -0.686575  , -0.887781  , -0.999375  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.999994  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.998512  ,  0.        ,  0.        ,  0.896794  ,  0.721543  , -0.02455   ,  0.727059  ,  0.460267  ,  0.0353382 ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.442449  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.0312717 ,  0.0222539 , -0.999257  , -0.708292  , -0.444285  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        , -0.896794  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        , -0.999511  , -0.999752  ,  0.0385293 , -0.70592   , -0.895885  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.69237   ,  0.        ,  0.        ,  0.        ,  0.        , -0.0312717 ,  0.        ,  0.        ,  0.        ,  0.        ,  0.0133568 , -0.680904  , -0.999688  , -0.729735  ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        , -0.721543  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.999511  ,  0.        ,  0.        ,  0.        ,  0.        , -0.999911  ,  0.732372  ,  0.0249773 , -0.683731  ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.421931  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.999699  ,  0.        ,  0.        ,  0.        ,  0.        , -0.0222539 ,  0.        ,  0.        ,  0.        , -0.0133568 ,  0.        ,  0.        ,  0.        , -0.430089  , -0.701423  , -0.995828  ],
#        [ 0.        ,  0.        ,  0.906628  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.02455   ,  0.        ,  0.        ,  0.        ,  0.        ,  0.999752  ,  0.        ,  0.        ,  0.        ,  0.999911  ,  0.        ,  0.        ,  0.        ,  0.902787  ,  0.712745  ,  0.0912467 ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.999939  ,  0.        ,  0.        ,  0.        ,  0.891844  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.686575  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.999257  ,  0.        ,  0.        ,  0.        ,  0.680904  ,  0.        ,  0.        ,  0.430089  ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        , -0.0110347 ,  0.        ,  0.        ,  0.        , -0.452342  ,  0.        ,  0.        ,  0.        ,  0.        , -0.727059  ,  0.        ,  0.        ,  0.        ,  0.        , -0.0385293 ,  0.        ,  0.        ,  0.        , -0.732372  ,  0.        ,  0.        , -0.902787  ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.893343  ,  0.        ,  0.        ,  0.        ,  0.999984  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.887781  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.708292  ,  0.        ,  0.        ,  0.        ,  0.999688  ,  0.        ,  0.        ,  0.701423  ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.449375  ,  0.        ,  0.        ,  0.        ,  0.00563031,  0.        ,  0.        ,  0.        ,  0.        , -0.460267  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.70592   ,  0.        ,  0.        ,  0.        , -0.0249773 ,  0.        ,  0.        , -0.712745  ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.70804   ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.999375  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.444285  ,  0.        ,  0.        ,  0.        ,  0.729735  ,  0.        ,  0.        ,  0.995828  ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.706172  ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        , -0.0353382 ,  0.        ,  0.        ,  0.        ,  0.        ,  0.895885  ,  0.        ,  0.        ,  0.        ,  0.683731  ,  0.        ,  0.        , -0.0912467 ],
#        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])
# v0 = np.array([ 0.373818,  0.210006,  0.      , -0.579807, -0.223472,  0.      ,  0.628346, -0.783823,  0.      ,  0.872047,  0.79509 ,  0.      ,  0.681132,  0.605348,  0.      ,  0.164952, -0.252971,  0.      , -0.913964, -0.750728,  0.      , -0.910003, -0.243079,  0.      , -0.464429,  0.727438,  0.      ])

pd_data = data_import.read_files_to_pd_dataframe(
    [f"../outs/grid/itr_{i}.xml.out" for i in range(500)]
)


In [45]:

i = 181
Q = pd_data['Q'][i]
N = pd_data['N'][i]
v0 = pd_data['v0'][i]
Minv = pd_data['Minv'][i]
ipopt_soln = pd_data['ipopt_sol'][i]

# Policy Iteration Algo

In [46]:

def get_policy(Q, x, b):
    """
    updates policy to the next policy,
    returns error
    """
    policy = []
    err2 = 0
    y = np.dot(Q, x) + b
    for i in range(len(x)):
        if y[i] < x[i]:
            policy.append(i)
        err2 += min(x[i], y[i]) ** 2    # x should be > 0, while y should be as close to 0 as possible
    return err2 ** 0.5, policy


def update_value(policy, Q, b, use_cg = True):
    """
    returns the next x given the policy
    """
    I = np.eye(len(b))
    policy_matrix = np.zeros((b.shape[0], b.shape[0]))
    for p in policy:
        policy_matrix[p,p] = 1
    A = np.dot(
            np.dot(
                policy_matrix,
                Q
            ),
            policy_matrix
        ) + I - policy_matrix
    rhs = -np.dot(policy_matrix, b) 
    lst_sqr_soln = np.linalg.lstsq(A , rhs)[0]
    cg_soln = scipy.sparse.linalg.cg(A , rhs , tol=1e-12)[0]
    if use_cg:
        return cg_soln
    else:
        return lst_sqr_soln


In [47]:
np.set_printoptions(linewidth=1000)

In [51]:
# what is a correct policy?
# ipopt_soln = np.array([7.75540e+00, 4.74150e+00, 5.29072e-07, 1.47006e+01, 7.63778e-07, 9.12397e-08, 6.96872e-07, 3.95227e-08, 5.42195e-08, 2.71711e+01, 1.22910e+01, 1.32105e+01, 6.24783e-08, 3.95232e-07, 2.02076e-06, 5.51228e-07, 5.40347e-07, 3.53198e+01, 2.10580e+01, 7.60474e-08, 1.62990e+01, 6.16939e-08, 3.68516e+01, 1.42129e-07, 4.23235e-08, 2.45350e-07, 2.37094e+01])

correct_policy = [i for i in range(len(ipopt_soln)) if ipopt_soln[i] > 1e-6]
print(correct_policy)

[0, 1, 3, 9, 10, 11, 14, 17, 18, 20, 22, 26]


In [54]:

# or does it...? maybe we are using wrong error function?
def obj_func(Minv, N, v0, sol):
    # assume elastic collision
    return 0.5 * (N @ sol + v0).T @ Minv @ (N @ sol + v0)

def obj_func_prime(Minv, N, v0, sol):
    err = 0
    b = 2 * N.T @ v0
    # print(N.T @ Minv @ N @ sol)
    y = (N.T @ Minv @ N @ sol) + b
    for i in range(len(sol)):
        err += min(sol[i], y[i]) ** 2    # x should be > 0, while y should be as close to 0 as possible
    return err ** 0.5

obj_func_prime(Minv, N, v0, ipopt_soln)

1.0539805724202076e-05

In [52]:
max_itrs = 100
m_tol = 1e-09
CoR = 1


# our "manual" policy iteration
# b = np.dot(N_prime.T, (1 + CoR) * v0)
b = np.dot(N.T, (1 + CoR) * v0)
x = np.zeros(b.shape[0])

# policy_guess = [0, 1, 3, 9, 10, 11, 14, 17, 18, 20, 22, 26]
policy_guess = correct_policy
"""
we cycle between
[0, 1, 3, 9, 10, 11, 14, 17, 18, 20, 22, 26] <<< this is the one we should be stopping on!
[0, 1, 3, 9, 10, 11, 17, 18, 20, 22, 23, 26]
"""

"""
ipopt solution:
[7.75540e+00     4.74150e+00    5.29072e-07 1.47006e+01 7.63778e-07 9.12397e-08 6.96872e-07 3.95227e-08 5.42195e-08 2.71711e+01 1.22910e+01 1.32105e+01 6.24783e-08 3.95232e-07 2.02076e-06 5.51228e-07 5.40347e-07 3.53198e+01 2.10580e+01 7.60474e-08 1.62990e+01 6.16939e-08 3.68516e+01 1.42129e-07 4.23235e-08 2.45350e-07 2.37094e+01]


closest PI gets to:
[7.46347457e+00  5.29292007e+00 -1.42108547e-14  1.41606336e+01 -1.06581410e-14 -7.10542736e-15  3.90798505e-14  1.42108547e-14  5.32907052e-15  2.75668024e+01  2.43949953e+01  1.74714976e+02 -5.68434189e-14 -4.23516474e-22 -1.67848493e+02  1.72563323e-31 -4.93038066e-32  3.63863909e+01  1.89936848e+01  0.00000000e+00  2.45334801e+00 -6.16297582e-33  4.15968867e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00  1.88435882e+02]

ipopt & PI formatted
[7.75540  4.74150  0 1.47006e+01 0 0 0 0 0 2.71711e+01  1.22910e+01 1.32105e+01 0  0  2.02076e-06 0 3.53198e+01 2.10580e+01 0 1.62990e+01    0 3.68516e+01     0 0 0 2.37094e+01]
[7.46347  5.29292  0 1.41606e+01 0 0 0 0 0 2.75668e+01  2.43950e+01 1.74715e+02 0  0 -1.67848e+02 0 3.63864e+01 1.89937e+01 0 2.45334801e+00 0 4.15968867e+01  0 0 0 1.88435882e+02]
"""

policy = []
error = 0.0

last_x = x

for n_iter in range(max_itrs):
    error, policy = get_policy(Q, x, b)
    if error <= m_tol:
        print("converged!")
        print(repr(x))
        break
    
    print(policy)
    # if not error <= 0.5:
    x = update_value(policy, Q, b, False)
    print(x)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
[ 32.84648102  19.82717115 -13.82642097  61.67718279 -20.29745928 -25.99516068  11.2391921  -26.23257914  -7.22487417  27.58576281  23.82203394  44.15938303 -30.62166746 -25.65917846   5.9919527  -15.94924349  20.63509016  43.21101387  16.6717282   -0.09068336 -10.47767146 -28.42913726  83.52215835 -16.69556999  13.92002031  -3.19742883  45.54074446]
[0, 1, 3, 6, 9, 10, 11, 14, 16, 17, 18, 22, 24, 26]
[-2.42991216e+02  2.55566111e+02  3.55271368e-15  6.03869494e+00 -1.66977543e-13 -2.20268248e-13 -2.51888567e+02  2.25597319e-13  5.41788836e-14  5.09677521e+01  2.87608362e+01  5.46357748e+02  1.35003120e-13 -4.26325641e-14 -5.64278185e+02  0.00000000e+00 -1.02817561e+01  6.02620237e+01  8.96132830e+00  8.78224055e-32 -4.93038066e-32  3.69778549e-32  4.65634925e+01  1.23259516e-31 -4.79488735e+01  0.00000000e+00  5.83867979e+02]
[1, 3, 9, 10, 11, 12, 17, 18, 20, 22, 23, 26]
[-0.00000000e+00

/tmp/ipykernel_165390/1635178028.py:32: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  lst_sqr_soln = np.linalg.lstsq(A , rhs)[0]
