In [1]:
import scipy
import numpy as np

In [2]:
A = np.array([
    [2, 1, -1],
    [1, 2, 1],
    [-1, 1, 2]
])
evals, evects = np.linalg.eig(A)

In [3]:
def sqrt(x):
    return x ** 0.5
Q = np.array( [
    [1/sqrt(3), 1/sqrt(2), -1/sqrt(6)],
    [-1/sqrt(3), 1/sqrt(2), 1/sqrt(6)],
    [1/sqrt(3), 0, 2/sqrt(6)]
])

# Q @ np.array([
#     [0,0,0],
#     [0,3,0],
#     [0,0,3]
# ]) @ Q.T
Q.T @ A @ Q

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.76337239e-17,  3.00000000e+00, -1.80316523e-17],
       [ 2.48422528e-18,  5.37383387e-17,  3.00000000e+00]])

In [4]:
(3 ** 0.5) * evects

array([[ 1.41421356,  1.        ,  0.50800051],
       [ 0.70710678, -1.        ,  1.3970014 ],
       [-0.70710678,  1.        ,  0.88900089]])

In [5]:
A @ np.array([-1,0,1])

array([-3,  0,  3])

In [6]:
9 * A @ A

array([[ 54,  27, -27],
       [ 27,  54,  27],
       [-27,  27,  54]])

In [7]:
A @ A @ A @ A

array([[ 54,  27, -27],
       [ 27,  54,  27],
       [-27,  27,  54]])

In [8]:
col1 = 1/(2 ** 0.5) * np.array([1, 0, -1])
col2 =  np.array([0, 1, 0])
col3 = 1/(3 ** 0.5) * np.array([1, 1, 1])
Q = np.array([
    col1, col2, col3
]).T

Q.T @ np.array([
    [-1, 0,0], [0,0,0], [0,0,1]
]) @ Q

array([[ 2.23711432e-17,  0.00000000e+00, -8.16496581e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-8.16496581e-01,  0.00000000e+00, -2.94613014e-18]])

In [15]:
l = 0
A = np.array([
    [2 - l  , 1     , 0],
    [1      , 1 - l , -1],
    [0      , -1    , 2 - l]
])

g = (sqrt(2) / sqrt (3)) * np.array([-1,2,1])
np.linalg.norm(g.T @ A @ g)

0.0

In [17]:
l = 0
A = np.array([
    [ 2 - l ,-2     ,-4],
    [-2     , 5 - l ,-2],
    [-4     ,-2     , 2 - l]
])
np.linalg.eig(A)

(array([ 6., -3.,  6.]),
 array([[ 0.74535599, -0.66666667,  0.17972129],
        [-0.2981424 , -0.33333333, -0.9399256 ],
        [-0.59628479, -0.66666667,  0.29024151]]))

In [29]:
v1 = 1/3 * np.array([2, 1, 2])
v2 = np.array([-1/sqrt(5), 2/sqrt(5), 0])
v3 = np.array([-4/(3 * sqrt(5)), -2/(3 * sqrt(5)), 5 / (3 * sqrt(5))])
print(v1)
print(A @ v1 / -3)

[0.66666667 0.33333333 0.66666667]
[0.66666667 0.33333333 0.66666667]


In [169]:
A = np.array([
    [-1, 1],
    [1, 1]
])

L = np.array([
    [1, 0],
    [0, 2]
])

x = np.array([1,0.5])

(A @ L @ A.T)
# x.T @ (A.T @ L @ A) @ x


# np.linalg.eig(
#     (A.T @ L @ A)
# )
(A.T @ L @ A)


array([[3, 1],
       [1, 3]])

In [173]:
A = np.array([
    [1, 0],
    [3, 1]
])

x = np.array([1,-1])

x.T @ A @ x

-1